### ISSUE TITLE
Rework the Calendar, Cafeteria, etc. Picker UIs

### ISSUE THREAD

**Issue by nerdsupremacist** [TCA-Team/iOS#237] opened 2018-02-13 20:20 UTC
The Picker UI is kind of showing it's age.
We should consider changing it for something different.

I'm open to suggestions

**Comment by mathiasquintero** [comment] 2018-02-13 20:20
@TG908 Any thoughts?

**Comment by TG908** [comment] 2018-02-19 22:59
I like the idea of getting rid if the Picker UI. These are the options I can think of: 
![img_1793](https://user-images.githubusercontent.com/7985149/36400370-d078cf1c-15d0-11e8-9cea-be0a57288431.png)
![Uploading IMG_1791.JPG…]()
![Uploading IMG_1794.png…]()
![Uploading IMG_1792.JPG…]()

**Comment by mathiasquintero** [comment] 2018-02-20 00:40
- Paginated Tabs at the top would have to be scrolling. Kind of like Amazon Prime Videos. Because of the number of options.
- Alert Sheet seems fine but we should look for something that makes it clear that you can choose what is being displayed.
- The Card UI of the Reminders App is excellent though a bit complicated.

And perhaps for the maps in the room finder we should ditch selection entirely and have the maps shown like a photo gallery you can swipe through. Like facebook.

**Comment by TG908** [comment] 2018-02-20 14:38
> And perhaps for the maps in the room finder we should ditch selection entirely and have the maps shown like a photo gallery you can swipe through. Like facebook.

Dont really like that. How hard would it be to create a proper map?

**Comment by mathiasquintero** [comment] 2018-02-20 15:09
We'd have to get the coordinates for the rooms. 
And I don't see them anywhere. 
Perhaps they're on some private api for the room finder.
Or we could try fetching the first map, match the name to a coordinate we know, find the red dot and and apply scaling and offset to get the coordinates. So pretty hard

**Comment by TG908** [comment] 2018-02-20 16:59
could we maybe use the roomfinder images as a map overlay...?

**Comment by thellmund** [comment] 2018-06-19 11:22
Low priority as we currently need to work on more important issues.

**Comment by thellmund** [comment] 2018-06-30 16:59
Duplicate of #266.

**Closed by thellmund** 2018-06-30 16:59 UTC
Labels: Low Priority, UI, enhancement
